/*
 * OTA Usage Example
 *
 * This example shows how to use the enhanced OTA functionality
 * in your application.
 */

#include <stdio.h>
#include <string.h>
#include "esp_log.h"
#include "crid_ota_web.h"

static const char *TAG = "OTA_EXAMPLE";

// Example MD5 checksum (this would be generated by the ota_util.py script)
// For demonstration purposes only - in practice, generate this from your actual firmware
static const uint8_t example_firmware_md5[16] = {
    0xd4, 0x1d, 0x8c, 0xd9, 0x8f, 0x00, 0xb2, 0x04,
    0xe9, 0x80, 0x09, 0x98, 0xec, 0xf8, 0x42, 0x7e
};

void ota_example_init(void)
{
    // Optional: Set expected MD5 for firmware validation
    // Comment this out to disable MD5 checking
    crid_ota_set_expected_md5(example_firmware_md5);

    // Initialize OTA web server
    esp_err_t err = crid_ota_web_init();
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "Failed to initialize OTA web server: %s", esp_err_to_name(err));
        return;
    }

    ESP_LOGI(TAG, "OTA web server initialized successfully");
}

void ota_example_check_status(void)
{
    // Check OTA status periodically
    if (crid_ota_is_in_progress()) {
        int progress = crid_ota_get_progress();
        ESP_LOGI(TAG, "OTA in progress: %d%%", progress);
    } else {
        ota_state_t state = crid_ota_get_state();
        switch (state) {
            case OTA_IDLE:
                ESP_LOGI(TAG, "OTA is idle");
                break;
            case OTA_COMPLETED:
                ESP_LOGI(TAG, "OTA completed successfully");
                break;
            case OTA_FAILED:
                ESP_LOGE(TAG, "OTA failed: %s", crid_ota_get_last_error());
                break;
            default:
                break;
        }
    }
}